# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20161102_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('who', 'whom')]),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('who', 'whom')]),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('who', 'whom')]),
        ),
    ]
