# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Media_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='media',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, null=True, to='user_profile.HashTag', verbose_name='Hashtag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_disc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.FileField(upload_to='', verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
